name: 
  /home/daniel/anaconda-workspace/sample-ml-multiple-unsupervised-technique-analysis/env
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - prince
  - pandas
  - plotly
  - pingouin
  - scikit-learn=1.7.2
  - numpy
  - scipy
  - jupyterlab
  - matplotlib
  - openpyxl
  - factor_analyzer
  - python=3.12
prefix: 
  /home/daniel/anaconda-workspace/sample-ml-multiple-unsupervised-technique-analysis/env
